baseURL = "https://eventmodeling.org/"
languageCode = "en-us"
title = "Event Modeling"
theme = "ezhil"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
disqusShortname = "eventmodeling-org"

[params]
	subtitle = "Designing Modern Information Systems"
	# Number of posts to show in recent posts list.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page.
	excludedTypes = ["page"]
	disableDisqusTypes = ["page"]
	featherIconsCDN = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Resources"
url = "/resources"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/event-modeling"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/eventmodeling"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
